#! /bin/sh

xrandr --output DisplayPort-4 --mode 3440x1440 --rate 143.97 &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4
#
# Autostart
#
# Restore Wallpaper
feh --no-fehbg --bg-scale $HOME/Downloads/color.jpg &
# Notifications
/usr/bin/dunst &
# Network Applet
nm-applet --indicator &
# Launch Polybar
$HOME/.config/polybar/launch.sh &
# Execute Picom
picom &
# Fix Cursor
xsetroot -cursor_name left_ptr &

bspc config border_width      3
bspc config window_gap          13

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        "#7aa2f7"
bspc config normal_border_color         "#303446"
bspc config active_border_color         "#303446"
